
bioconda::pybiomart
conda-forge::scanpy=1.7.2
conda-forge::numpy=1.24.4
conda-forge::pandas=1.5.3
bioconda::scrublet=0.2.3
jupyter=1.0.0
conda-forge::umap-learn
conda-forge::louvain
conda-forge::matplotlib-venn
bioconda::gseapy
pip3 bbknn 1.6.0
pip install spatialde