project:
  type: website
  # output directory used on gh-pages branch. format: YYMM
  output-dir: "docs"
  render: 
    - "!compiled/"
    - "!LICENSE"
    - "!scripts"
    - "!tmprepo"
    - "!*.Rmd"
    - "!*.md"
    - "!*.ipynb"
    - "*.qmd"

website:
  image: "assets/logos/nbis.png"
  favicon: "assets/favicon.png"
  navbar:
    logo: "assets/logos/nbis-scilifelab.png"
    logo-alt: "nbis-scilifelab-logo."
    right:
      - text: "Home"
        href: "index.html"
      - text: "Schedule"
        href: "home_schedule.html"
      - text: "Contents"
        href: "home_contents.html"
      - text: "Precourse"
        href: "home_precourse.html"
      - text: "Syllabus"
        href: "home_syllabus.html"
      - text: "Info"
        href: "home_info.html"
  page-footer:
    border: false
    left: "2023 [NBIS](https://nbis.se) | [GPL-3 License](https://choosealicense.com/licenses/gpl-3.0/)"
    right: "Published with [Quarto](https://quarto.org/) v<?quarto.version?>"

format:
  html:
    quarto-required: ">=1.2.2"
    include-in-header: "assets/fonts/head.html"
    theme: "assets/css/custom.scss"
    smooth-scroll: true
    toc: true
    toc-depth: 4
    toc-location: right
    number-sections: true
    number-depth: 4
    code-fold: false
    code-tools: false
    code-copy: true
    code-overflow: wrap
    df-print: kable
    standalone: false
    fig-align: left
    title-block-banner: "#E9F2D1"
    callout-icon: false
    date:  last-modified
    date-format: "DD-MMM-YYYY"
    author: "Åsa Björklund  &  Paulo Czarnewski"
    lightbox: 
      match: auto
  revealjs:
    quarto-required: ">=1.2.269"
    include-in-header: "assets/fonts/head.html"
    theme: ["default","assets/css/custom.scss"]
    width: 1280
    height: 720
    transition: "fade"
    transition-speed: "fast"
    smaller: false
    incremental: false
    scrollable: false
    slide-number: true
    progress: true
    date:  last-modified
    date-format: "DD-MMM-YYYY"
    fig-align: left
    chalkboard: true
    callout-icon: false
    title-slide-attributes:
      data-background-image: "assets/images/cover.png"
      data-background-size: "cover"
      data-background-opacity: "1"
    header-logo-left: ../../assets/logos/nbis.png
    header-logo-right: ../../assets/logos/scilifelab.png
    author: "Åsa Björklund  &  Paulo Czarnewski"

metadata-files:
  - labs/_metadata.yml
  
knitr:
  opts_chunk:
    results: hold

execute:
  eval: true
  echo: true
  warning: false
  message: false
  freeze: true

filters:
  - assets/custom.lua
  - reveal-header
  - lightbox

# used site-wide wherever uppmax project ids are used
uppmax_compute: naiss2023-22-862
uppmax_storage: naiss2023-22-862

# location options are stockholm or online. For rendering the info page.
# one or more separated by commas or semicolon. online doesn't display any location info.
location: uppsala
assistants:
 - "AJ: Anna Johansson"
 - "BV: Björn Viklund"
 - "DA: Dag Ahren"
 - "FB: Franziska Bonath"
 - "JH: Jason Hill"
 - "JB: Joakim Bygdell"
 - "JA: Juliana Assis"
 - "KL: Katarina Lejonlid"
 - "KB: Kristina Benevides"
 - "LK: Linda Köhn"
 - "LV: Louella Vasquez"
 - "MD: Martin Dahlö"
 - "MG: Maxime Garcia"
 - "ML: Malin Larsson"
 - "MM: Markus Mayrhofer"
 - "NN: Nina Norgren"
 - "OVP: Olga Vinnere Pettersson"
 - "PA: Prasoon Agarwal"
 - "PP: Paul Pyl"
 - "RF: Roy Francis"
 - "VVH: Vincent van Hoef"
 - "SD: Sebastian DiLorenzo"
schedule_message: "Schedule is preliminary and may be subject to changes."
colors:
  primary: "#95b540"
  secondary: "#E9F2D1"

