## conda requirements for all packages needed to run the scanpy tutorials
# install with:  conda env create -n scanpy -f environment_scanpy.yaml
# then run conda activate scanpy

channels:
 - bioconda
dependencies
 - scanpy
 - notebook


# additional dependencies to install by pip (after running conda activate scanpy)
# pip install mnnpy 
# pip install MulticoreTSNE