## conda requirements for all packages needed to run the scanpy tutorials
# install with:  conda env create -n scRNAseq2020 -f environment.yml
# then run: source activate scRNAseq2020
name: scRNAseq2021

channels:
 - conda-forge
 - bioconda
 - defaults
 - anaconda
 - r
 - rdonnelly
 - psi4

dependencies:
 - rstudio
 - bioconductor-scater
 - bioconductor-scran
 - bioconductor-singlecellexperiment
 - bioconductor-slingshot
 - bioconductor-tradeseq
 - bioconductor-destiny
 - bioconductor-rhdf5
 - bioconductor-fgsea
 - r-enrichr
 - r-devtools
 - r-biocmanager
 - r-dplyr
 - r-igraph
 - r-seurat>=3.1.2
 - r-umap
 - r-grr
 - r-hdf5r
 - r-bookdown
 - r-venn
 - r-uwot
 - notebook
 - jupyter_contrib_nbextensions
 - multicore-tsne
 - requests
 - wget
 - compilers
 - pip
 - pip:
   - mnnpy
   - scanpy
   - scanorama
   - numba
   - python-igraph
   - louvain
   - leidenalg
   - matplotlib-venn
   - python-annoy
