## conda requirements for all packages needed to run the scanpy tutorials
# install with:  conda env create -n scRNAseq2020 -f environment.yml
# then run: source activate scRNAseq2020

channels:
 - conda-forge
 - bioconda
 - defaults
 - anaconda
 - rdonnelly
dependencies:
 - rstudio
 - bioconductor-scater
 - bioconductor-scran=1.14
 - bioconductor-singlecellexperiment
 - r-biocmanager
 - r-dplyr
 - r-igraph
 - r-seurat
 - r-umap
 - r-grr
 - r-hdf5r
 - r-bookdown
 - r-venn
 - umap-learn
 - scanpy=1.4.4.post1
 - numba=0.42.0 # compatible with scanpy 1.4.4.
 - notebook
 - jupyter_contrib_nbextensions
 - multicore-tsne
 - python-igraph
 - louvain
 - leidenalg
 - matplotlib-venn
 - python-annoy
 - requests=2.22.0
 - wget=1.19.4  # For compatibility with genomeinfodbdata (currently broken)
 - libgfortran
 #- pip
 #- pip:
 #  - mnnpy
 #  - scanorama
