## conda requirements for all packages needed to run the scanpy tutorials
# install with:  conda env create -n rlabs -f environment.yml
# then run: source activate rlabs

channels:
 - bioconda
 - conda-forge
 - defaults
 - anaconda
 - rdonnelly
dependencies:
 - r-base=3.5
# - rstudio=1.1.456
 - rstudio=1.2.502
 - bioconductor-biomart=2.38
 - bioconductor-flowpeaks=1.28
 - bioconductor-genomeinfodbdata=1.2.0
 - bioconductor-scater=1.10
 - bioconductor-scran=1.10
 - bioconductor-singlecellexperiment=1.4
 - bioconductor-sva=3.30
 - bioconductor-org.Hs.eg.db
 - bioconductor-org.Mm.eg.db
 - r-devtools=2.1.0
 - r-biocmanager=1.30
 - r-data.table=1.11
 - r-dbscan=1.1
 - r-dplyr=0.8
 - r-fields=9.6
 - r-igraph=1.2
 - r-ineq=0.2
 - r-optparse=1.6
 - r-pheatmap=1.0
 - r-rafalib=1.0
 - r-rcolorbrewer=1.1
 - r-scales=1.0
 - r-seurat=3.0.1
 - r-vegan=2.5
 - r-umap=0.2
 - umap-learn=0.3.7
 - r-grr=0.9.5
 - r-hdf5r=1.2.0
 - scanpy=1.4.4.post1
 - numba=0.42.0 # compatible with scanpy 1.4.4.
 - notebook
 - jupyter_contrib_nbextensions
 - multicore-tsne
 - python-igraph
 - louvain
 - leidenalg
 - matplotlib-venn
 - requests=2.22.0
 - r-bookdown
 - r-venn=1.7
 - wget=1.19.4  # For compatibility with genomeinfodbdata (currently broken)
 - r-venn

#Additional packages to install:
# pip install mnnpy