
channels:
 - bioconda
 - conda-forge
 - defaults
 - anaconda
 - rdonnelly
dependencies:
 - rstudio=1.2.502
 - bioconductor-slingshot=1.4.0
 - bioconductor-scran=1.14
 - bioconductor-tradeseq
 - r-umap=0.2
 - umap-learn=0.3.7
 - wget
 - r-hdf5r=1.2.0
 - r-bookdown
 - r-seurat=3.0.2
 - umap-learn=0.3.7
 - r-uwot
