
channels:
 - bioconda
 - conda-forge
 - defaults
 - anaconda
 - rdonnelly
dependencies:
 - rstudio
 - bioconductor-slingshot=1.4.0
 - bioconductor-scran
 - bioconductor-tradeseq
 - wget
 - r-bookdown
 - r-seurat=3.0.2
 - umap-learn=0.3.7
 - r-uwot
